//author: autogenerated
//modified by: Jeff Shepherd
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  isLoggedIn: boolean = true;
  assignment: string = "Excercise 2.3 - Data Binding";
  title = 'enhanced-profile-app';
}
